require_relative '../book.rb'
require_relative '../classroom.rb'
require_relative '../decorator.rb'
require_relative '../person.rb'
require_relative '../rental.rb'
require_relative '../student.rb'
require_relative '../teacher.rb'
require_relative '../trimmer_decorator.rb'
require_relative '../nameable.rb'
require_relative '../capitalize_decorator.rb'

require 'yaml'
